language: python
python:
- 3.8.3
install:
- pip install -r .devcontainer/requirements.txt
branches:
  only:
  - master
script:
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ];
      then pytest && bash .travis/bump_and_push.sh && python setup.py bdist_wheel;
      else pytest;
  fi'
deploy:
  provider: pypi
  user: __token__
  password:
    secure: cn9iPWlKU0meW+s+TBibTfGimI8WTEmhCp++AGFD0K9yold4yHDLdVJkqC4IE9O1URI1IoSdKM86baM+jQOWqjQExlLJcO+ST/yFVVvI/HQaxzHnnQXsuSlLPIDxWSoBqqBP7DTOU/073KoMPVsEk7ppkCAWNfX2/hzMxfueW6Rk/zCZ9f1NjConVUju0y92dHnUBA770Aqrg6kSi7dohsJuOoTFhOoCkJ2ouWME4dlAJp6Ex+OLVNKXw9XrorpwDJ8KJvVAYf77B9o7UFvRmw4jWCfz3Irqh1LRbsjQyH5dj5wICi5aAMP4zNMB1FGJxsGsDVPJJ0Q9g17U4mfAJendlXHGsz3zu5RjmDDQFWpliEXSZVU7+Rm0I6MT7Jcd4+Zt+mNWHIaTN6pEHpMjErRNVsUIPb0s4lAP4+CaioBG6rp185c2DTF18WKjAD6ngZTm4shYLRVwUPaTz+Q4mVlQO+b+UwbGuBiBGfpIVpts15U2vb1tfuHBBdiOsi64Fe434mN87uufT7oYHfBDsbUTPcm8ABTK7voRPq5sfdnhSkhlKCaIXtt2Ny/52sNK1jVzpETz/Vm1FQmH4Ng35z4f2HrTWIhy8D79JbqwshAJpyzBgWIrE6U1OdKtcjN+SIQlzK++OvzRYt3c/NUlrZ1CAQy7KfuCBcGjDLt4jVg=
  skip_cleanup: true
  distributions: bdist_wheel
notifications:
  slack:
    rooms:
      secure: RuI2zn/gbyz6WmBDRNfj0U9HyJAyvvUB46NlDp1dUBuE1aXH+kn2PFo+XceOUyLKNI5DLEvx7UlPA+GpqZHzzKydupoUWwJ8uUmpzjsGn7elQK5rm44qX1WRgkbW4sgiRcS4eGjpEyRTpSMkO9PzD+/wCSLUT3NuEeEtjPYKoPwUCkXDH3uzlTwblDEtBF+wQY0yu/PjB41Zxj5Ojr6i6QoUXeI9EdmaZ4LenrPc4syf8ceLM48J2R+KXQIKfqZgDCVNBGsV5hbVmFNbCSA7tpKDBqfkGGWAZ+53/H+3mb3uzLqPbz8Y4OMsmMLCiCUmmbLTOF2jJJUcMZ/I1c2zQ37Zycylatkp7HdMruw0pw/ndPjL5zbsswzCqDVNxaL8ZILAHrG7QnB8RvFAcspXDZ4x7AY8BAnhukbMzWhMIYELwNBHPW04oDlR31Hmanp+yxfDX5uJw1WZFlFJJcIDE7VacDRXrIpT5CkoHvLNs+CjyItwW0L4jxpQB0BE+lfchQKMorLnmUeaO7tbLtxW7JESGiigIegMtfF3mlLcOQgifVErpl2dLhdIRY6Q1B0u9DvL3hqmlESYBQSU89twwXyuVRFPkqE0fpyAJNPBBEtJAbk2//k3sG8Z2oimRul3OsKI/zugko7feF18PJ61ZkZ4Clb++nExI5dVVLcb4NE=
env:
  global:
    secure: TuIaIADC2h2lOWXMomXRjth8+8dRAcneJ2ngc9rrkTnoBkCyro5xK45qhrZ+W2l451VvS6yNAC3XD7VwzMwSTYVSIb0lc6Sh7HP5Sgac5gje1XX6pJKHre9igtsQTEpzZ0rJIvL5QRE99sUYCF+pm/VGA2djiBoQcvuD6YGl3DXGi4P8raIMsVYVGiVaVRMBGlO9vpax9GnyzHeI3XzP+2ml9tXHFq8dcFxeY5DYhzbQmlx9oDx4Qg+aLmlp0bSEqXitLBPiEWq04wkiotX3HULdjitQLk8Cl1wpMkxl1MuQzjyJM7TA5CKMpcjyv1bJHH8+zB4H8LepPv1Wi/PeVktSIgjljp4/j7TgBJgELI3FiPLaNUigSPH947SuG+CHFZJ68uFJSxCpQ4joHvwOWJlOnWYKjz1Z/5SyMcbyCRlaXQEAvZVgHJC4AHJSmuYehJHckAgk5fbDlid9OUqE58zEnbZ9I6q8xNam7SZm1CCE5Y6Nlp6F9Io3s0Pn5xhU2+eBUXIhOeipKevHxLgZLjtnWWfgX4FgzOinG/zQM+BaZBFV7662KTH01dBqQXL6NsHfwBKsjgHzED2ndkSQ3fC73ETxYaHwdlzi0mRrR/8pUXw/8F3dnfizeaogKI+tNr6Stf3WokxD+rTJbek8UMNXQpgAeeJOfMiYYtCcEf4=
